-- Seed funders from Filip's internal MCA Funder Manual.
--
-- Source: C:\Users\fkozi\OneDrive\Radna površina\COMMERA FUNDING\
--         (referenced) MCA_Funder_Manual.docx
--
-- Generated by scripts/import_funders_from_manual.py. The manual is
-- operator-curated by Filip's team — every threshold here is
-- operator-real per .claude/rules/operating-principles.md #4 (this
-- supersedes migration 035's placeholder seed which was deleted by
-- migration 045).
--
-- §8 Splash Advance (broker/aggregator), §9 Big Think Capital (35%
-- affiliate split), §10 Bizi Connect (loan marketplace) are excluded —
-- per the manual itself, those three "do not publish underwriting
-- boxes" and are not direct funders.
--
-- Idempotent via ON CONFLICT (name) DO NOTHING — operator-edited rows
-- are never overwritten. To replace with fresh extraction, manually
-- DELETE the row first, then re-apply.


INSERT INTO funders (
  name, active, min_monthly_revenue, min_credit_score, min_months_in_business, max_positions, accepts_stacking, min_advance, max_advance, typical_factor_low, typical_factor_high, excluded_industries, excluded_states, requires_coj, charges_merchant_advance_fees, contact_name, contact_email, contact_phone, submission_email, auto_decline_conditions, notes_residual, guidelines_extracted_at
) VALUES
-- §2 Logic Advance
(  'Logic Advance',
   true,
   25000.00,
   500,
   6,
   5,
   true,
   NULL,
   1500000.00,
   1.25,
   1.37,
   ARRAY['Automotive Dealership', 'Real Estate', 'Financial Services', 'Trucking — only restricted if <24 months TIB OR <$100K revenue', 'Construction — only restricted if <24 months TIB OR <$100K revenue']::TEXT[],
   '{}'::TEXT[],
   false,
   false,
   'Erik',
   'Erik@logicadvancegroup.com',
   '(516) 261-2730',
   'Submissions@logicadvancegroup.com',
   ARRAY['Bouncing MCA payments', 'Active defaults', 'Lowered or modified MCA payments', 'Recent bankruptcy', 'Multiple fundings in recent months (stacking pattern)']::TEXT[],
   'Logic Advance has 4 tiers (Elite / Premium / Standard / High-Risk). Quick Reference reflects loosest tier (High-Risk). Full tier breakdown lives in manual §2; consider tier-aware FunderTier rows in a follow-up.',
   NOW()),
-- §3 Velocity Capital Group
(  'Velocity Capital Group',
   true,
   20000.00,
   500,
   12,
   4,
   true,
   NULL,
   2000000.00,
   NULL,
   NULL,
   ARRAY['Bail Bonds', 'Gas Stations', 'Investment Firms', 'Law Firms', 'Travel Agencies', 'Religious Organizations', 'Logistics', 'Moving', 'Trucking', 'Nail Salons', 'Lending Platforms', 'Vehicle/Auto Dealer', 'Real Estate', 'Staffing', 'Vape Shops', 'Pawn Shops']::TEXT[],
   '{}'::TEXT[],
   false,
   false,
   '',
   '',
   '',
   'subs@velocitycg.com',
   ARRAY['Less than 3 monthly deposits', 'Deposit volume under $20K per month', 'Open bankruptcies (with other MCAs in place)', 'Excessive returns / NSFs', 'Negative activity or history with other MCA providers', 'Fraudulent documentation', 'Below minimum FICO (500)', 'Excessive transfers', 'Tax lien judgment above $200K']::TEXT[],
   '',
   NOW()),
-- §4 SwiftSource Funding
(  'SwiftSource Funding',
   true,
   40000.00,
   NULL,
   12,
   NULL,
   true,
   NULL,
   750000.00,
   1.37,
   NULL,
   ARRAY['Casinos', 'Financial Services']::TEXT[],
   '{}'::TEXT[],
   false,
   false,
   '',
   '',
   '',
   'Subs@SwiftFunding.net',
   '{}'::TEXT[],
   'Swiftsource: ''2nd & up only'' — does not fund 1st position. max_positions field semantics need operator review.',
   NOW()),
-- §5 Shor Capital
(  'Shor Capital',
   true,
   20000.00,
   NULL,
   NULL,
   NULL,
   false,
   NULL,
   NULL,
   1.45,
   1.49,
   ARRAY['Financial Institutions', 'Collection Agencies', 'Used or New Auto Sales', 'Non-Profit Organizations', 'Bail Bonds', 'Check Cashing', 'Religious Entities', 'Real Estate Investment', 'Staffing Agencies', 'Travel Agencies', 'Oil Drilling']::TEXT[],
   '{}'::TEXT[],
   false,
   false,
   '',
   '',
   '(877) 218-8043',
   'submissions@shor.capital',
   '{}'::TEXT[],
   '',
   NOW()),
-- §6 United Capital Source
(  'United Capital Source',
   true,
   25000.00,
   575,
   12,
   2,
   true,
   NULL,
   NULL,
   NULL,
   NULL,
   '{}'::TEXT[],
   '{}'::TEXT[],
   false,
   false,
   '',
   'ColleenS@GoUcs.com',
   '646-448-1711',
   'isosubmissions@unitedcapitalsource.com',
   '{}'::TEXT[],
   'UCS is multi-product (MCA / Term / SBA / Equipment / LOC). Quick Reference reflects MCA-product criteria; other products have different boxes in manual §6.',
   NOW()),
-- §7 Highland Hill Capital
(  'Highland Hill Capital',
   true,
   30000.00,
   500,
   12,
   8,
   true,
   NULL,
   5000000.00,
   1.499,
   1.499,
   ARRAY['Investors / Bail Bonds']::TEXT[],
   ARRAY['CA', 'VA', 'TX']::TEXT[],
   false,
   false,
   '',
   '',
   '954-947-8724',
   'Submissions@highlandhillcap.com',
   '{}'::TEXT[],
   'Highland Hill: subordinate positions 2nd–8th (does NOT fund 1st). Specialty reverse-consolidation funder.',
   NOW())
ON CONFLICT (name) DO NOTHING;
