"""Generic disclosure templates that are NOT prescribed by any specific state.

The Tier 2 acknowledgment is a deliberate fallback for states whose
general law (usury caps, UCC treatment) governs commercial financing
without a state-prescribed MCA disclosure form. It cites the general
law verbatim from the StateRegulation entry — never invents text.

Tier 1 templates live separately, under `compliance/templates/`, with
one file per state's prescribed form. Those must be exact line-by-line
matches to the regulator's published format.
"""

from __future__ import annotations

# Jinja autoescape protects every variable below. Operators never embed
# raw HTML — the template only formats text fields.
TIER2_GENERIC_ACKNOWLEDGMENT = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Commercial Financing Acknowledgment — {{ state_name }}</title>
</head>
<body>
<h1>Commercial Financing Acknowledgment</h1>

<p>This acknowledgment confirms that the commercial financing transaction
identified below is governed by the general commercial-financing law of
the State of {{ state_name }}. {{ state_name }} has not enacted an
MCA-specific disclosure statute as of the verification date below.</p>

<h2>Transaction</h2>
<ul>
  <li><strong>Merchant:</strong> {{ business_name }}</li>
  <li><strong>State:</strong> {{ state_name }} ({{ state }})</li>
  <li><strong>Principal:</strong> ${{ principal }}</li>
  <li><strong>Factor:</strong> {{ factor }}</li>
  <li><strong>Total repayment:</strong> ${{ total_repayment }}</li>
</ul>

<h2>Governing law</h2>
<p>This transaction is governed by:
{{ general_law_citation }}.
See <a href="{{ citation_url }}">{{ citation_url }}</a>.</p>

<h2>Regulatory posture</h2>
<p>{{ notes }}</p>

<hr>
<p><small>Generated by AEGIS on {{ rendered_at }}. Verified
{{ verified_date }}. This acknowledgment is not a state-prescribed
disclosure form; it is a record that the parties acknowledge the
governing law cited above.</small></p>
</body>
</html>
"""


__all__ = ["TIER2_GENERIC_ACKNOWLEDGMENT"]
