#!/bin/bash
# One-time rclone install on the prod Hetzner box.
# Run as root:
#   ssh -i ~/.ssh/aegis_ci_deploy root@5.161.51.105 \
#     "bash /opt/aegis/scripts/setup_rclone_onedrive.sh"
set -e
echo "=== Installing rclone ==="
curl https://rclone.org/install.sh | sudo bash
echo "=== Installing FUSE3 ==="
apt-get install -y fuse3
mkdir -p /mnt/onedrive && chown aegis:aegis /mnt/onedrive
mkdir -p /var/log/aegis && chown aegis:aegis /var/log/aegis

echo ""
echo "=== IMPORTANT: headless auth flow (you are SSH'd in; no browser here) ==="
echo ""
echo "The default rclone OAuth flow tries to open a browser at"
echo "  http://127.0.0.1:53682/ on THIS server"
echo "which your Windows browser cannot reach over SSH. That is why"
echo "  'site can't be reached'"
echo "happens if you accidentally pick 'Use auto config = y'."
echo ""
echo "Use the headless flow instead. Two options — pick whichever is easier."
echo ""
echo "------------------------------------------------------------"
echo "OPTION A — interactive 'rclone authorize' on Windows"
echo "------------------------------------------------------------"
echo ""
echo "1. In THIS ssh session, run:"
echo "     rclone config"
echo ""
echo "2. Walk the prompts:"
echo "     n              -> new remote"
echo "     name:          onedrive"
echo "     Storage:       onedrive    (type the word, not the number)"
echo "     client_id:     <press Enter — blank>"
echo "     client_secret: <press Enter — blank>"
echo "     Edit advanced config? n"
echo "     Use auto config? n         <-- IMPORTANT: NO, not y"
echo ""
echo "3. rclone prints something like:"
echo "     rclone authorize \"onedrive\""
echo "   STOP here. Leave this ssh session open."
echo ""
echo "4. Open a SEPARATE PowerShell window on your Windows laptop."
echo "   If rclone isn't installed locally:"
echo "     winget install Rclone.Rclone"
echo "   Then run the EXACT command rclone printed:"
echo "     rclone authorize \"onedrive\""
echo "   A real browser opens. Log in with your Microsoft account."
echo "   rclone prints a long config token (a JSON-looking blob)."
echo "   Copy the ENTIRE token to the clipboard."
echo ""
echo "5. Come back to THIS ssh session. Paste the token when rclone"
echo "   prompts for 'config_token>'. Press Enter."
echo ""
echo "6. Finish the prompts:"
echo "     drive_type:   onedrive     (or pick option 1 for OneDrive Personal)"
echo "     Confirm:      y"
echo "     Quit config:  q"
echo ""
echo "------------------------------------------------------------"
echo "OPTION B — configure entirely on Windows, scp the config"
echo "------------------------------------------------------------"
echo ""
echo "Often simpler. See deploy/RUNBOOK.md § OneDrive rclone setup"
echo "for the full walkthrough. Summary:"
echo ""
echo "  1. winget install Rclone.Rclone        # if not installed"
echo "  2. PowerShell:  rclone config           # auto-config WORKS on Windows"
echo "  3. Follow the same prompts; the auto browser flow works locally"
echo "  4. scp \$env:APPDATA\\rclone\\rclone.conf to this server"
echo "  5. Then run: bash /opt/aegis/scripts/setup_rclone_mount.sh"
echo ""
echo "------------------------------------------------------------"
echo ""
echo "When the rclone config file exists (either path), run:"
echo "  bash /opt/aegis/scripts/setup_rclone_mount.sh"
