"""Processor-statement brand detector tests (mp Phase 6.6 / Stage 2C).

``detect_processor`` reads the first couple of pages of extractable
text and returns one of ``stripe`` / ``square`` / ``bank`` / ``ambiguous``.
The detector is the gate that decides which extractor the upload
pipeline invokes — wrong call here means wasted Bedrock tokens and
a result the downstream validator will reject.

The synthetic corpus PDFs (generated by
``scripts.generate_processor_corpus``) double as detection fixtures
since each one prints multiple brand signatures by design.
"""

from __future__ import annotations

from pathlib import Path

import pymupdf

from aegis.parser.processor.detect import detect_processor

_CORPUS = Path(__file__).resolve().parents[1] / "fixtures" / "corpus" / "processor"


def test_detect_stripe_clean() -> None:
    """Stripe brand wins. A few signatures are generic enough to also
    appear in Square statements ("Gross volume"); what matters is that
    Stripe signatures clear the threshold and Square signatures don't."""
    result = detect_processor(_CORPUS / "stripe_clean.pdf")
    assert result.brand == "stripe"
    assert result.stripe_hits >= 2
    assert result.square_hits < 2


def test_detect_square_clean() -> None:
    result = detect_processor(_CORPUS / "square_clean.pdf")
    assert result.brand == "square"
    assert result.square_hits >= 2
    assert result.stripe_hits < 2


def test_detect_returns_bank_on_random_pdf(tmp_path: Path) -> None:
    """A PDF that mentions neither processor → ``bank`` so the upload
    pipeline falls through to the bank parser."""
    pdf = tmp_path / "plain.pdf"
    doc = pymupdf.open()
    page = doc.new_page(width=612, height=792)
    page.insert_text(
        (72, 72),
        "Plain bank statement, no processor signatures here.\nDeposit ACH 1234.56\n",
        fontsize=10,
    )
    doc.save(pdf)
    doc.close()
    result = detect_processor(pdf)
    assert result.brand == "bank"
    assert result.stripe_hits == 0
    assert result.square_hits == 0


def test_detect_returns_ambiguous_when_both_brands_present(tmp_path: Path) -> None:
    """PDF mentions BOTH Stripe and Square strongly → ``ambiguous`` so
    the upload pipeline can fail closed instead of guessing."""
    pdf = tmp_path / "mixed.pdf"
    doc = pymupdf.open()
    page = doc.new_page(width=612, height=792)
    page.insert_text(
        (72, 72),
        "\n".join(
            [
                "stripe.com",
                "Stripe, Inc.",
                "Activity summary",
                "squareup.com",
                "Block, Inc.",
                "Sales summary",
            ]
        ),
        fontsize=10,
    )
    doc.save(pdf)
    doc.close()
    result = detect_processor(pdf)
    assert result.brand == "ambiguous"
    assert result.stripe_hits >= 2
    assert result.square_hits >= 2


def test_detect_corrupt_pdf_defaults_to_bank(tmp_path: Path) -> None:
    """Pymupdf failure must NOT crash the detector. Returning ``bank``
    lets the upload pipeline route to the bank parser (the safer
    fallback — bank parser will fail loudly on a corrupt PDF rather
    than silently mishandling it)."""
    bad = tmp_path / "corrupt.pdf"
    bad.write_bytes(b"not a pdf at all")
    result = detect_processor(bad)
    assert result.brand == "bank"


def test_passing_mention_does_not_flip_brand(tmp_path: Path) -> None:
    """A document with ONE passing mention of "Stripe" but no other
    signature hits stays as ``bank`` — the threshold protects against
    false positives."""
    pdf = tmp_path / "mention_only.pdf"
    doc = pymupdf.open()
    page = doc.new_page(width=612, height=792)
    page.insert_text(
        (72, 72),
        "We accept payments via Stripe.\nBalance summary as of date.\n",
        fontsize=10,
    )
    doc.save(pdf)
    doc.close()
    result = detect_processor(pdf)
    assert result.brand == "bank"
